"""Typed live certification flow for advisory workspace handoff and rationale review."""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from typing import Any, Protocol, cast

import httpx

from scripts.live_policy_evaluation_support import Assertion, PostJson, RequestJson


class WorkspaceScenario(Protocol):
    """Scenario values required to exercise a stateful workspace."""

    @property
    def portfolio_id(self) -> str: ...

    @property
    def as_of_date(self) -> str: ...


class AssertAuthorityPosture(Protocol):
    """Typed adapter for the shared simulation/risk authority assertion."""

    def __call__(self, *, portfolio_id: str, proposal_body: dict[str, Any]) -> None: ...


@dataclass(frozen=True)
class LiveWorkspacePrimitives:
    """Dependencies supplied by the live validator without importing its module."""

    post_json: PostJson
    request_json: RequestJson
    assertion: Assertion
    assert_authority_posture: AssertAuthorityPosture


def _assert_rationale_response(
    *,
    primitives: LiveWorkspacePrimitives,
    portfolio_id: str,
    workspace_id: str,
    response_body: dict[str, Any],
) -> dict[str, Any]:
    assertion = primitives.assertion
    assertion(
        response_body.get("generated_by") == "lotus-ai",
        f"{portfolio_id}: workspace rationale was not generated by lotus-ai",
    )
    evidence = response_body.get("evidence")
    assertion(
        isinstance(evidence, dict) and evidence.get("workspace_id") == workspace_id,
        f"{portfolio_id}: workspace rationale evidence lost workspace identity",
    )
    workflow_pack_run = response_body.get("workflow_pack_run")
    assertion(
        isinstance(workflow_pack_run, dict),
        f"{portfolio_id}: workspace rationale omitted workflow-pack run posture",
    )
    workflow_pack = cast(dict[str, Any], workflow_pack_run)
    checks = (
        (workflow_pack.get("workflow_authority_owner") == "lotus-advise", "run owner drifted"),
        (workflow_pack.get("runtime_state") == "COMPLETED", "run was not completed"),
        (workflow_pack.get("review_state") == "AWAITING_REVIEW", "lost awaiting-review posture"),
        (
            workflow_pack.get("supportability_status") == "ACTION_REQUIRED",
            "lost action-required posture",
        ),
        (
            isinstance(workflow_pack.get("allowed_review_actions"), list)
            and "REVISE" in workflow_pack["allowed_review_actions"]
            and "SUPERSEDE" in workflow_pack["allowed_review_actions"],
            "omitted bounded replacement review actions",
        ),
    )
    for condition, detail in checks:
        assertion(condition, f"{portfolio_id}: workspace rationale {detail}: {workflow_pack}")
    return workflow_pack


def _assert_rationale_review_action(
    *,
    primitives: LiveWorkspacePrimitives,
    portfolio_id: str,
    initial_run_id: str,
    replacement_run_id: str,
    review_action: dict[str, Any],
) -> tuple[str, str]:
    assertion = primitives.assertion
    review_run = review_action.get("workflow_pack_run")
    assertion(
        isinstance(review_run, dict),
        f"{portfolio_id}: workspace rationale review action omitted workflow-pack run",
    )
    workflow_pack = cast(dict[str, Any], review_run)
    checks = (
        (workflow_pack.get("run_id") == initial_run_id, "returned the wrong run"),
        (workflow_pack.get("replacement_run_id") == replacement_run_id, "lost replacement lineage"),
        (workflow_pack.get("review_state") == "SUPERSEDED", "review state drifted after supersede"),
        (
            workflow_pack.get("supportability_status") == "HISTORICAL"
            and workflow_pack.get("superseded") is True,
            "did not produce historical superseded posture",
        ),
        (
            isinstance(review_action.get("summary"), list) and bool(review_action["summary"]),
            "omitted summary evidence",
        ),
        ("assistant_output" not in review_action, "implied a rewritten narrative"),
    )
    for condition, detail in checks:
        assertion(
            condition,
            f"{portfolio_id}: workspace rationale review action {detail}: {workflow_pack}",
        )
    return str(workflow_pack["review_state"]), str(workflow_pack["supportability_status"])


def assert_live_workspace_flow(
    client: httpx.Client,
    *,
    primitives: LiveWorkspacePrimitives,
    advise_base_url: str,
    scenario: WorkspaceScenario,
) -> tuple[str, str, str, str]:
    """Certify workspace replay continuity and bounded advisor-rationale review state."""

    post_json = primitives.post_json
    request_json = primitives.request_json
    assertion = primitives.assertion
    portfolio_id = scenario.portfolio_id

    create_body = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces",
        expected_status=201,
        json_body={
            "workspace_name": f"Live parity {portfolio_id}",
            "created_by": "live-parity-validator",
            "input_mode": "stateful",
            "stateful_input": {
                "portfolio_id": portfolio_id,
                "as_of": scenario.as_of_date,
            },
        },
    )
    workspace = cast(dict[str, Any], create_body["workspace"])
    workspace_id = str(workspace["workspace_id"])
    assertion(
        workspace["resolved_context"]["portfolio_id"] == portfolio_id,
        f"{portfolio_id}: workspace resolved wrong portfolio context",
    )

    evaluated = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/evaluate",
        expected_status=200,
        json_body={},
    )
    latest_result = evaluated.get("latest_proposal_result")
    assertion(
        isinstance(latest_result, dict),
        f"{portfolio_id}: workspace evaluate missing proposal result",
    )
    primitives.assert_authority_posture(
        portfolio_id=portfolio_id,
        proposal_body=cast(dict[str, Any], latest_result),
    )

    saved = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/save",
        expected_status=200,
        json_body={"saved_by": "live-parity-validator", "version_label": "live-parity-baseline"},
    )
    saved_version = cast(dict[str, Any], saved["saved_version"])
    workspace_version_id = str(saved_version["workspace_version_id"])
    saved_risk_lens = cast(dict[str, Any], saved_version["replay_evidence"])["risk_lens"]
    assertion(
        isinstance(saved_risk_lens, dict) and saved_risk_lens.get("source_service") == "lotus-risk",
        f"{portfolio_id}: workspace saved replay evidence missing lotus-risk lens",
    )

    handoff = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/handoff",
        expected_status=200,
        json_body={"handoff_by": "live-parity-validator"},
        headers={"Idempotency-Key": f"live-workspace-handoff-{uuid.uuid4().hex}"},
    )
    assertion(
        handoff["handoff_action"] == "CREATED_PROPOSAL",
        f"{portfolio_id}: unexpected workspace handoff action {handoff['handoff_action']}",
    )
    handoff_proposal = cast(dict[str, Any], handoff["proposal"])
    version = cast(dict[str, Any], handoff_proposal["version"])
    proposal = cast(dict[str, Any], handoff_proposal["proposal"])
    primitives.assert_authority_posture(
        portfolio_id=portfolio_id,
        proposal_body=cast(dict[str, Any], version["proposal_result"]),
    )

    workspace_replay = request_json(
        client,
        method="GET",
        url=(
            f"{advise_base_url}/advisory/workspaces/{workspace_id}/saved-versions/"
            f"{workspace_version_id}/replay-evidence"
        ),
        expected_status=200,
    )
    proposal_replay = request_json(
        client,
        method="GET",
        url=(
            f"{advise_base_url}/advisory/proposals/{proposal['proposal_id']}/versions/"
            f"{version['version_no']}/replay-evidence"
        ),
        expected_status=200,
    )
    assertion(
        workspace_replay["evidence"]["risk_lens"]["source_service"] == "lotus-risk",
        f"{portfolio_id}: workspace replay evidence missing lotus-risk source",
    )
    assertion(
        proposal_replay["evidence"]["risk_lens"]["source_service"] == "lotus-risk",
        f"{portfolio_id}: proposal replay evidence missing lotus-risk source",
    )
    assertion(
        workspace_replay["subject"]["proposal_id"] == proposal["proposal_id"],
        f"{portfolio_id}: workspace replay subject missing proposal linkage",
    )
    assertion(
        proposal_replay["continuity"]["workspace_version_id"] == workspace_version_id,
        f"{portfolio_id}: proposal replay continuity missing workspace version linkage",
    )
    assertion(
        workspace_replay["hashes"]["evaluation_request_hash"]
        == proposal_replay["hashes"]["evaluation_request_hash"],
        f"{portfolio_id}: workspace/proposal replay hashes diverged after handoff",
    )

    first_rationale = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/assistant/rationale",
        expected_status=200,
        json_body={
            "requested_by": "live-parity-validator",
            "instruction": "Summarize the evaluated workspace rationale for review.",
        },
    )
    second_rationale = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/assistant/rationale",
        expected_status=200,
        json_body={
            "requested_by": "live-parity-validator",
            "instruction": "Refresh the rationale to produce a replacement review run.",
        },
    )
    first_run = _assert_rationale_response(
        primitives=primitives,
        portfolio_id=portfolio_id,
        workspace_id=workspace_id,
        response_body=first_rationale,
    )
    second_run = _assert_rationale_response(
        primitives=primitives,
        portfolio_id=portfolio_id,
        workspace_id=workspace_id,
        response_body=second_rationale,
    )
    initial_run_id = str(first_run["run_id"])
    replacement_run_id = str(second_run["run_id"])
    assertion(
        initial_run_id != replacement_run_id,
        f"{portfolio_id}: workspace rationale replacement run did not produce a new run id",
    )

    review_action = post_json(
        client,
        url=f"{advise_base_url}/advisory/workspaces/{workspace_id}/assistant/rationale/review-actions",
        expected_status=200,
        json_body={
            "run_id": initial_run_id,
            "action_type": "SUPERSEDE",
            "reviewed_by": "live-parity-validator",
            "reason": "Replacement rationale run supersedes the earlier draft.",
            "replacement_run_id": replacement_run_id,
        },
    )
    review_state, supportability_status = _assert_rationale_review_action(
        primitives=primitives,
        portfolio_id=portfolio_id,
        initial_run_id=initial_run_id,
        replacement_run_id=replacement_run_id,
        review_action=review_action,
    )
    return initial_run_id, replacement_run_id, review_state, supportability_status
